version: "3.5"
services:
  pcts_documents:
    container_name: pcts_documents
    # restart: unless-stopped
    build: .
    image: pcts_documents
    env_file: dev-env
    command: ["sh", "scripts/start_dev.sh"]
    ports:
      - 8000:8000
    networks:
      - pcts-network
    volumes:
      - .:/app
      - pip-cache:/usr/local/lib/python3.8/site-packages

volumes:
  pip-cache:
    name: pcts_documents-pip-cache

networks:
  pcts-network:
    name: pcts-network
    driver: bridge
