# Generated by Django 3.2.7 on 2021-09-04 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=240, verbose_name='Title')),
                ('url', models.CharField(max_length=1024, verbose_name='Url')),
                ('description', models.CharField(max_length=240, verbose_name='Title')),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
