# Generated by Django 3.2.7 on 2021-09-19 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Glossario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('palavra_chave', models.CharField(max_length=240)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Informacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fonte', models.CharField(max_length=240)),
                ('data_extracao', models.DateField(auto_now_add=True)),
                ('titulo', models.CharField(max_length=240)),
                ('teor_textual', models.CharField(max_length=2000)),
                ('autor', models.CharField(max_length=240)),
                ('dataPublicacao', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Document',
        ),
    ]
