name: CI/CD

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  integration:
    runs-on: ubuntu-latest
    env:
      GIT_SHA: ${{ github.sha }}

    steps:
      - uses: actions/checkout@v2

      - name: Stylesheet check
        run: echo 'stylesheet check'

      - name: Build image
        run: docker build -t pcts-documents .

      - name: Run tests
        run: |
          docker run \
            --env ENVIRONMENT=development \
            --env ALLOWED_HOSTS=* \
            --network ${{ job.container.network }} \
            --volume ${PWD}/:/app \
            pcts-documents bash -c \
            "python manage.py makemigrations && \
              python manage.py migrate && coverage run --source='.' \
              manage.py test && coverage xml"

  sonarAnalysis:
    needs: integration
    name: SonarCloud Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Analyze with SonarCloud
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  deploy_dev:
    if: github.ref == 'refs/heads/dev'
    needs: integration
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

  deploy_main:
    if: github.ref == 'refs/heads/main'
    needs: integration
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
